-- Editable amendment drafts: store a full agreement-style snapshot on the amendment row.
-- Amendments remain separate from signed parent agreements and persist line items separately.

alter table public.agreement_amendments
  add column if not exists source_agreement_id text,
  add column if not exists agreement_id text,
  add column if not exists agreement_number text,
  add column if not exists proposal_id text,
  add column if not exists deal_id text,
  add column if not exists lead_id text,
  add column if not exists agreement_relationship_type text,
  add column if not exists agreement_version integer,
  add column if not exists relationship_notes text,
  add column if not exists agreement_title text,
  add column if not exists agreement_date date,
  add column if not exists service_start_date date,
  add column if not exists service_end_date date,
  add column if not exists agreement_length text,
  add column if not exists account_number text,
  add column if not exists billing_frequency text,
  add column if not exists payment_term text,
  add column if not exists payment_terms text,
  add column if not exists po_number text,
  add column if not exists customer_name text,
  add column if not exists customer_legal_name text,
  add column if not exists customer_address text,
  add column if not exists customer_contact_name text,
  add column if not exists customer_contact_mobile text,
  add column if not exists customer_contact_email text,
  add column if not exists contact_id text,
  add column if not exists contact_name text,
  add column if not exists contact_email text,
  add column if not exists contact_phone text,
  add column if not exists contact_mobile text,
  add column if not exists customer_contact_phone text,
  add column if not exists company_email text,
  add column if not exists company_phone text,
  add column if not exists country text,
  add column if not exists city text,
  add column if not exists tax_number text,
  add column if not exists provider_name text,
  add column if not exists provider_legal_name text,
  add column if not exists provider_address text,
  add column if not exists provider_contact_name text,
  add column if not exists provider_contact_mobile text,
  add column if not exists provider_contact_email text,
  add column if not exists provider_signatory_email text,
  add column if not exists customer_official_signatory_name text,
  add column if not exists customer_official_signatory_title text,
  add column if not exists customer_signatory_name text,
  add column if not exists customer_signatory_title text,
  add column if not exists customer_signatory_email text,
  add column if not exists customer_signatory_phone text,
  add column if not exists provider_official_signatory_1_name text,
  add column if not exists provider_official_signatory_1_title text,
  add column if not exists provider_official_signatory_2_name text,
  add column if not exists provider_official_signatory_2_title text,
  add column if not exists provider_signatory_name text,
  add column if not exists provider_signatory_title text,
  add column if not exists provider_primary_signatory_name text,
  add column if not exists provider_primary_signatory_title text,
  add column if not exists provider_secondary_signatory_name text,
  add column if not exists provider_secondary_signatory_title text,
  add column if not exists provider_signatory_name_primary text,
  add column if not exists provider_signatory_title_primary text,
  add column if not exists provider_signatory_name_secondary text,
  add column if not exists provider_signatory_title_secondary text,
  add column if not exists terms_conditions text,
  add column if not exists generated_by text,
  add column if not exists gm_signed boolean not null default false,
  add column if not exists financial_controller_signed boolean not null default false,
  add column if not exists saas_total numeric(14,2) not null default 0,
  add column if not exists one_time_total numeric(14,2) not null default 0,
  add column if not exists tax numeric(14,2) not null default 0;

create index if not exists idx_agreement_amendments_source
on public.agreement_amendments (source_agreement_id);
