-- Keep the first scheduled payment anchored to the invoice due date for every write path,
-- including renewal/issue RPCs and direct schedule recalculations.
create or replace function public.anchor_invoice_payment_schedule_first_due_date()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.schedule_no = 1 then
    select i.due_date
      into new.due_date
      from public.invoices i
     where i.id = new.invoice_id;
  end if;
  return new;
end;
$$;

drop trigger if exists invoice_payment_schedule_first_due_date_anchor
  on public.invoice_payment_schedule;

create trigger invoice_payment_schedule_first_due_date_anchor
before insert or update of invoice_id, schedule_no, due_date
on public.invoice_payment_schedule
for each row
execute function public.anchor_invoice_payment_schedule_first_due_date();

-- Repair existing first installments that were generated by adding Net days again.
update public.invoice_payment_schedule schedule
   set due_date = invoice.due_date
  from public.invoices invoice
 where schedule.invoice_id = invoice.id
   and schedule.schedule_no = 1
   and schedule.due_date is distinct from invoice.due_date;
